
USE OUR_COMPANY;

CREATE TABLE DEPATMENTS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL
);

CREATE TABLE EMPLOYEES(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
date DATE, 
employe_email VARCHAR(255),
manager INT,
department INT NOT NULL,
CONSTRAINT FOREIGN KEY (department) REFERENCES DEPATMENTS(id)
);

CREATE TABLE PRODUCT(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
prise  INT NOT NULL,
category INT NOT NULL 
);


CREATE TABLE PRODUCTS(
id  VARCHAR(3) NOT NULL,
name VARCHAR(255) NOT NULL,
product INT NOT NULL,
CONSTRAINT FOREIGN KEY (product) REFERENCES PRODUCT(id),
CONSTRAINT uc_ProductID UNIQUE (id)
);

CREATE TABLE QUANTITY(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name  VARCHAR(3) NOT NULL,
CONSTRAINT FOREIGN KEY (name) REFERENCES PRODUCTS(uc_ProductID),
quantity_count INT NOT NULL
);

CREATE TABLE ORDER_PRODUCTS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
quantity VARCHAR(255) NOT NULL,
id_quantity INT NOT NULL,
id_orders INT NOT NULL,
CONSTRAINT FOREIGN KEY (id_quantity) REFERENCES QUANTITY(id)
);

CREATE TABLE CUSTOMERS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
email VARCHAR(255),
adress VARCHAR(255) NOT NULL,
discount VARCHAR(25) NOT NULL
);

CREATE TABLE ORDERS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
quantity VARCHAR(255) NOT NULL,
date DATE NOT NULL,
time TIME NOT NULL,
id_orders_products INT NOT NULL,
CONSTRAINT FOREIGN KEY (id_orders_products) REFERENCES ORDER_PRODUCTS(id),
totalprise DOUBLE(10,10) NOT NULL
);





